name: Text Embeddings Inference For CUDA

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to checkout'
        required: false
        default: main
        type: string
      runtime_compute_cap:
        description: 'runtime_compute_cap'
        required: false
        default: '80'
        type: string
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          repository: huggingface/text-embeddings-inference
          ref: ${{ github.event.inputs.branch }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-cuda
          push: true
          tags: zhixinlinchuan/text_embeddings_inference:main_20250611
          build-args: |
            CUDA_COMPUTE_CAP=${{ github.event.inputs.runtime_compute_cap }}
          
